import SupabaseProvider from "@/components/SupabaseAuthProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MainNav } from "@/components/MainNav";
import Link from "next/link";
import { ThemeProvider } from "@/components/ThemeProvider";
import { AuthButton } from "@/components/AuthButton";
import { Toaster } from "sonner"; // Import Toaster

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SupabaseProvider>
            <div className="container mx-auto flex min-h-screen flex-col">
              <header className="sticky top-0 z-40 w-full border-b bg-background">
                <div className="container flex h-16 items-center">
                  <div className="flex-1">
                    <Link href="/" className="items-center space-x-2 md:flex">
                      <span className="font-bold sm:inline-block">
                        Homomorphic Demo
                      </span>
                    </Link>
                  </div>
                  <div className="flex-1 flex justify-center">
                    <MainNav />
                  </div>
                  <div className="flex-1 flex justify-end">
                    <AuthButton />
                  </div>
                </div>
              </header>
              <main className="flex-1">{children}</main>
            </div>
          </SupabaseProvider>
        </ThemeProvider>
        <Toaster /> {/* Add Toaster component here */}
      </body>
    </html>
  );
}
